--                                                          coffee_Sales_Analysis (AMIT)

select * from coffee_sales

-- What are the unique store locations in the dataset?

select distinct store_location
from coffee_sales

-- How many transactions occurred on '02-06-2023'?

select count(transaction_id) as total_transactions_occured
from coffee_sales
where transaction_date = '02-06-2023'

-- What is the total bill for all transactions on '02-06-2023'?

select count(Total_Bill) as total_bills , transaction_date
from coffee_sales
where transaction_date = '02-06-2023'
group by transaction_date

-- How many transactions were made in the store with store_id 3?

select count(transaction_id) as total_transactions
from coffee_sales
where store_id = 3

-- Find the total quantity of 'Tea' sold.

select count(transaction_qty) as total_quantity, product_category
from coffee_sales
where product_category = 'Tea'
group by product_category

-- List all transactions where the total bill is greater than 3.

select count(*) as all_transactions 
from coffee_sales
where Total_Bill > 3

select count(transaction_id) as all_transactions
from coffee_sales
where Total_Bill > 3

-- What is the average unit price of products sold in the 'Astoria' store?

select round(avg(unit_price),2) as avg_unit_price
from coffee_sales
where store_location = 'Astoria'

-- Count the number of transactions for each day of the week.

select count(*) as total_transactions, Day_of_Week
from coffee_sales 
group by Day_of_Week
order by total_transactions desc

select count(transaction_id) as all_transactions, Day_of_Week
from coffee_sales
group by Day_of_Week
order by all_transactions desc


-- Find the total number of transactions for each month.

select count(*) as total_transaction, Month
from coffee_sales
group by Month
order by total_transaction

-- Retrieve all transactions where the transaction quantity is 1

select count(transaction_id) as transaction_id , transaction_qty
from coffee_sales
where transaction_qty = 1
group by transaction_qty

-- What is the highest total bill in the dataset?

select max(total_bill) as highest_total_bill
from coffee_sales

-- List all transactions sorted by transaction time

select transaction_id, transaction_time
from coffee_sales


-- Count the number of 'Peppermint' tea transactions.

select count(product_detail) as total_transaction , product_detail
from coffee_sales
where product_detail = 'Peppermint'
group by product_detail

-- Find the total revenue generated by 'Large' size products.

select round(sum(total_bill),0) as total_revenue
from coffee_sales
where Size = 'Large'

-- Retrieve transactions that occurred on a Friday.

select transaction_id , Day_Name
from coffee_sales
where Day_Name = 'Friday'
group by Day_Name, transaction_id

-- Calculate the total bill for each product type.

select round(sum(total_bill),2) as total_bills, product_type
from coffee_sales
group by product_type
order by total_bills desc

-- What is the minimum unit price in the dataset?

select round(min(unit_price) ,2)* 100 as minimum_price
from coffee_sales

-- List all transactions with a unit price of 3.

select transaction_id , unit_price
from coffee_sales
where unit_price = 3
group by unit_price, transaction_id

-- Find the total quantity of 'Brewed herbal tea' sold.

select sum(transaction_qty) as total_quantity
from coffee_sales
where product_type = 'Brewed herbal tea'



--  Count the number of transactions in the month of June.

select count(transaction_id) as total_transactions
from coffee_sales
where Month_Name = 'June'


-- List the distinct product categories in the dataset.

select distinct product_category 
from coffee_sales

-- Find the total revenue generated by each store location.

select round(sum(total_bill),0) as total_revenue , product_category
from coffee_sales
group by product_category
order by total_revenue desc

-- Count the number of transactions for each product size.

select count(transaction_id) as total_transactions, size
from coffee_sales
group by Size
order by total_transactions desc

--  Count total revenue for each product size.

select sum(transaction_qty) as total_revenue, size
from coffee_sales
group by Size
order by total_revenue desc

-- What is the total bill for transactions occurring on Thursdays?

select round(sum(total_bill),0) as total_bill
from coffee_sales
where Day_Name = 'Thursday'

-- Retrieve all transactions with a total bill of exactly 3.

select transaction_id, Total_Bill
from coffee_sales
where Total_Bill = 3
group by Total_Bill , transaction_id

-- Find the total quantity of products sold for each product type.

select count(transaction_qty) as total_quantity, product_type
from coffee_sales
group by product_type
order by total_quantity desc

--  Calculate the total bill for each day of the week.

select round(sum(total_bill),0) as total_bill, Day_of_Week
from coffee_sales
group by Day_of_Week
order by total_bill desc


--                                                                THANK YOU